#!/bin/bash

CONFIG="$HOME/.config/hypr/themes/wofi/config"
STYLE="$HOME/.config/hypr/themes/wofi/style.css"
COLORS="$HOME/.config/hypr/themes/wofi/colors"

if [[ ! $(pidof wofi) ]]; then
  wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
  pkill wofi
fi
